services:

  app:
    build: .
    image: graber
    container_name: graber
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=user
      - DB_NAME=quotidienne2
    networks:
      - mysql_net

networks:
  mysql_net:
    external: true  # Используем уже созданную сеть