version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: loterie_db
    ports:
      - "3306:3306"
    networks:
      - app_network  # Assurer qu'il est sur un réseau spécifique

  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=loterie_db
    networks:
      - app_network  # Assurer qu'il est sur un réseau spécifique
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "main.py"]

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app_network  # Assurer qu'il est sur un réseau spécifique

networks:
  app_network:
    driver: bridge  # Assurer qu'ils sont sur un réseau commun