-- Таблица Q4_fois: все 10000 комбинаций (n1,n2,n3,n4) и количество выпадений каждой в Q4.
-- Процедура пересоздаёт таблицу и заполняет из Q4.

DELIMITER //

DROP PROCEDURE IF EXISTS fill_Q4_fois//

CREATE PROCEDURE fill_Q4_fois()
BEGIN
  DROP TABLE IF EXISTS Q4_fois;

  CREATE TABLE Q4_fois (
      n1 TINYINT UNSIGNED NOT NULL,
      n2 TINYINT UNSIGNED NOT NULL,
      n3 TINYINT UNSIGNED NOT NULL,
      n4 TINYINT UNSIGNED NOT NULL,
      fois INT UNSIGNED NOT NULL DEFAULT 0,
      PRIMARY KEY (n1, n2, n3, n4)
  );

  INSERT INTO Q4_fois (n1, n2, n3, n4, fois)
  SELECT
    all_combos.n1,
    all_combos.n2,
    all_combos.n3,
    all_combos.n4,
    IFNULL(q.count, 0) AS fois
  FROM (
      SELECT a.num AS n1, b.num AS n2, c.num AS n3, d.num AS n4
      FROM
        (SELECT 0 AS num UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
         UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS num UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
         UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS num UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
         UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS num UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
         UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
  ) AS all_combos
  LEFT JOIN (
      SELECT n1, n2, n3, n4, COUNT(*) AS count
      FROM Q4
      GROUP BY n1, n2, n3, n4
  ) AS q
  ON all_combos.n1 = q.n1 AND all_combos.n2 = q.n2 AND all_combos.n3 = q.n3 AND all_combos.n4 = q.n4;
END//

DELIMITER ;
