services:

  backup:
    image: mysql
    container_name: mysql_backup
    volumes:
      - ./backup.sh:/backup.sh
      - ./backups:/backups
    entrypoint: ["/bin/sh", "-c", "/backup.sh"]
    restart: "no"
    networks:
      - mysql_net

networks:
  mysql_net:
    external: true  # Используем уже созданную сеть