CREATE DATABASE IF NOT EXISTS quotidienne CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS toutourien CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

GRANT ALL PRIVILEGES ON quotidienne.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON toutourien.* TO 'user'@'%';
FLUSH PRIVILEGES;