version: '3'

services:
    
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080