services:

  db:
    image: mysql
    # build: . Если есть Dockerfile
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quotidienne2  # Создаем БД
      MYSQL_USER: user
      MYSQL_PASSWORD: q
    volumes:
      - ./sql:/docker-entrypoint-initdb.d  # Загрузка SQL скриптов при старте
      - ./DB:/var/lib/mysql/  # Для персистентности данных
    ports:
      - "3306:3306"  # Открываем порт 3306
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"  # Открываем порт для Adminer
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
