services:

  app:
    build: .
    image: scripts
    container_name: scripts
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=user 
    networks:
      - mysql_net
    
    stdin_open: true
    tty: true
    restart: "no"   # ← вот это важно

networks:
  mysql_net:
    external: true  # Используем уже созданную сеть