version: '2'

services:

  app:
    build: .
    image: apache:test
    container_name: apache-test
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"

# context: .
# dockerfile: Dockerfile